[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy",
    "mkl-devel",
    "mkl-static"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*", "cp3{8,9,10}-*linux_i686"]

test-requires = ["pytest", "numpy"]
test-command = ["pytest --capture=no {project}/tests"]

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel show {wheel} --ignore-in-wheel & delvewheel repair -w {dest_dir} --ignore-in-wheel {wheel}"

[tool.cibuildwheel.linux]
before-all = [
    "yum install curl zip unzip tar",
    "git clone https://github.com/Microsoft/vcpkg.git",
    "vcpkg/bootstrap-vcpkg.sh",
    "export VCPKG_INSTALLATION_ROOT=$(pwd)/vcpkg"
    ]
