[environment]
python-version = "3.11"
python-platform = "all"
root = ["roughpy_jax"]

[src]
include = [
    "roughpy_jax",
]
exclude = [
    "roughpy_jax/tests/",
]
respect-ignore-files = true

[analysis]
respect-type-ignore-comments = true
replace-imports-with-any = ["roughpy._roughpy", "roughpy_jax._rpy_jax_internals"]

[rules]
all = "warn"
empty-body = "ignore"
too-many-positional-arguments = "ignore"
unresolved-attribute = "ignore"
unknown-argument = "ignore"


[[overrides]]
include = ["tests/**", "benchmarks/**", "examples/**"]

[overrides.rules]
possibly-unresolved-reference = "warn"

[[overrides]]
include = ["roughpy_jax/intervals.py"]

[overrides.rules]
unsupported-operator = "ignore"

[[overrides]]
include = ["roughpy_jax/ops.py"]

[overrides.rules]
invalid-assignment = "ignore"
invalid-argument-type = "ignore"
invalid-parameter-default = "ignore"
invalid-type-arguments = "ignore"
invalid-type-form = "ignore"
unresolved-import = "ignore"