# This was generated by the AI Assistant to find what depends on boost-fusion

import json


def find_dependencies(file_path, target_dependency):
    with open(file_path, 'r') as file:
        vcpkg_data = json.load(file)

    dependents = []

    for package in vcpkg_data.get("dependencies", []):
        if isinstance(package, dict) and "dependencies" in package:
            if target_dependency in package["dependencies"]:
                dependents.append(package["name"])
        elif isinstance(package, str):
            if package == target_dependency:
                dependents.append(vcpkg_data["name"])

    if dependents:
        print(f"The following packages depend on '{target_dependency}':")
        for dep in dependents:
            print(f"- {dep}")
    else:
        print(f"No packages directly depend on '{target_dependency}'.")


# Usage example:
find_dependencies('vcpkg.json', 'boost-fusion')