name: roughpy-jax-pytests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: &generic-ignore-paths
      - "examples/**"
      - "doc/**"
      - "README.md"
      - "CHANGELOG"
      - "tools/*.py"
      - ".github/workflows/build_wheels.yml"
      - ".github/dependabot.yml"
      - ".github/ISSUE_TEMPLATE/**"
      - "branding/**"
      - ".gitignore"
      - "CMakePresets.json"
      - "THANKS.txt"
      - "LICENSE.txt"
      - "VERSION.txt"
      - "CITATION.cff"
      - ".gitignore"

  pull_request:
    # branches: [ "main" ] FIXME uncomment; disabled to test merge int 220-roughpy-jax
    paths-ignore: *generic-ignore-paths

env:
  BUILD_TYPE: RelWithDebInfo
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Setup gha caching for vcpkg
      uses: actions/github-script@v7
      with:
        script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Python dependencies
      shell: bash
      run: |
        python -m pip install numpy ninja pytest jax "pybind11<3.0.0"

    - name: setup vcpkg
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git tools/vcpkg

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DROUGHPY_BUILD_TESTS=ON -DROUGHPY_JAX=ON
      env:
        CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
        MACOSX_DEPLOYMENT_TARGET: 11.0.0
        VCPKG_FORCE_SYSTEM_BINARIES: 1
        CMAKE_GENERATOR: "Ninja"

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}

    - name: PyTests
      shell: bash
      run: pytest -sv roughpy_jax/
      env:
        PYTHONPATH: ${{ github.workspace }}
